### ISSUE TITLE
npm install failing on new install

### ISSUE THREAD

**Issue by baldpope** [t2t2/obs-tablet-remote#124]
was able to clone and run npm install, but failing

```
npm ERR! Linux 4.4.0-190-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/obs-tablet-remote/npm-debug.log

```
attached debug.log from npm install
[npm-debug.log](https://github.com/t2t2/obs-tablet-remote/files/8301920/npm-debug.log)

**Comment by t2t2** [comment]
```
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
```

too ancient versions of nodejs & npm for support

**Comment by baldpope** [comment]
Yea, took me a few minutes to realize I was that far behind, primarily because of old ubuntu installation (16.04).  Upgraded to 18 last night and now getting errors related to packages needing update, and to 'fix' with npm audit fix, which also results in errors (attached).

[npm_audit_fix_error.log](https://github.com/t2t2/obs-tablet-remote/files/8305340/npm_audit_fix_error.log)
