### ISSUE TITLE
'npm install' fails: error: no matching member function for call to 'Set'

### ISSUE THREAD

**Issue by yurivict** [t2t2/obs-tablet-remote#67]
```
$ npm install

> yorkie@2.0.0 install /usr/ports/multimedia/obs-websocket/obs-tablet-remote/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done


> fibers@4.0.1 install /usr/ports/multimedia/obs-websocket/obs-tablet-remote/node_modules/fibers
> node build.js || nodejs build.js

gmake: Entering directory '/usr/ports/multimedia/obs-websocket/obs-tablet-remote/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:899:12: error: no matching member function for call to 'Set'
                        target->Set(sym_yield, yield);
                        ~~~~~~~~^~~
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/fibers.cc:903:8: error: no matching member function for call to 'Set'
                        fn->Set(sym_yield, yield);
                        ~~~~^~~
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/fibers.cc:909:12: error: no matching member function for call to 'Set'
                        target->Set(uni::NewLatin1Symbol(isolate, "Fiber"), fn);
                        ~~~~~~~~^~~
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3547:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3550:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/fibers.cc:927:27: error: no matching member function for call to 'Get'
        if (did_init || !target->Get(uni::NewLatin1Symbol(isolate, "Fiber"))->IsUndefined()) {
                         ~~~~~~~~^~~
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3594:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:3597:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/fibers.cc:206:25: error: no matching member function for call to 'Set'
                info.GetReturnValue().Set(handle);
                ~~~~~~~~~~~~~~~~~~~~~~^~~
../src/fibers.cc:838:17: note: in instantiation of function template specialization 'uni::Return<v8::Object>' requested here
                                return uni::Return(current->handle, info);
                                            ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4096:18: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'bool' for 1st argument
  V8_INLINE void Set(bool value);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4097:18: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'double' for 1st argument
  V8_INLINE void Set(double i);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4098:18: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'int32_t' (aka 'int') for 1st
      argument
  V8_INLINE void Set(int32_t i);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4099:18: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'uint32_t' (aka 'unsigned int') for
      1st argument
  V8_INLINE void Set(uint32_t i);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4090:18: note: candidate template ignored: could not match 'Global' against 'Persistent'
  V8_INLINE void Set(const Global<S>& handle);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4092:18: note: candidate template ignored: could not match 'TracedReferenceBase' against 'Persistent'
  V8_INLINE void Set(const TracedReferenceBase<S>& handle);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4094:18: note: candidate template ignored: could not match 'Local' against 'Persistent'
  V8_INLINE void Set(const Local<S> handle);
                 ^
/home/yuri/.cache/node-gyp/13.10.1/include/node/v8.h:4109:18: note: candidate template ignored: could not match 'S *' against 'Persistent<v8::Object>'
  V8_INLINE void Set(S* whatever);
                 ^
5 errors generated.
gmake: *** [fibers.target.mk:114: Release/obj.target/fibers/src/fibers.o] Error 1
gmake: Leaving directory '/usr/ports/multimedia/obs-websocket/obs-tablet-remote/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System FreeBSD 12.1-STABLE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /usr/ports/multimedia/obs-websocket/obs-tablet-remote/node_modules/fibers
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@4.0.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yuri/.npm/_logs/2020-04-04T04_51_33_839Z-debug.log
```

**Comment by sweetasdude** [comment]
I tried on docker (on qnap) and on windows based nodejs (new to both)  and install failed to. From the logs something to do with the the vue cli.  component.  Whilst I don't have a solution to that. I just downloaded all the js/css/and html resources from the demo page, using chrome inspector and slightly edited the html and they seem to work fine running on a local webserver.
